language: rust
env:
  global:
matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: nightly
    dist: xenial
    sudo: required
  - env: TARGET=armv7-unknown-linux-gnueabihf
    rust: nightly
    allow_fail: true
    dist: xenial
    sudo: required
  - env: TARGET=x86_64-unknown-linux-gnu DEPLOY=1
    rust: nightly
    dist: bionic
    sudo: required
  - env: TARGET=armv7-unknown-linux-gnueabihf
    rust: nightly
    allow_fail: true
    dist: bionic
    sudo: required
  allow_failures:
  - allow_fail: true
branches:
  only:
  - master
  - travis-ci
  - heroku-prod
  - heroku-staging
  - "/^v.*$/"
before_install:
- set -e
- lsb_release -a
install:
- sh .ci/install.sh
- source ~/.cargo/env || true
script:
- bash .ci/script.sh
after_script: set +e
deploy:
  provider: heroku
  api_key:
    secure: hDkK7zATxGrBar2l+DNO+yLL2o8FldQB6o/wQh0NQD9s77KMuDKvoBCHRvbTKZLS1m6746ncDfe3vAWzTPjqyxdawONIaWJG39d0GfW2qAtFyfrMWvBBsmpG3xf3HjIuyXTBfIoAPOupmmFclPJ2wOjR40n2jPn46/mKsgxiIx4Y+41rqtL8+Jk1i3h5+hAbI8UoiEmo64A63jESeLA4Q8x7m0rlcvreBDFgYs5Xux0SBqnqCOhWva+jW00ewxe+oC4e1FSWjfRkht4AjGaWkSrFrF4X8tIvVVsylz7vrAjEiCx3b3rhG52EdXBuLrD4eyPk5CYwcpIHbNNf14wnCXcVbyIDadg1+qnJ6/HddG4fGoZqJjN16PcB4Yfp8cqidgVVrLKbPHEF8VcNr22hgh5LlmRSNDKAsXCLNMegtM3dd7cxtmq42F+C+HIxBReUpjHMOujEX9qCVWdKwtLyXNiql+cyKtw+VtAaEmEx2xrcRYcmp/bM4W15PyQpHFG5dphMi7Wssnu70FVH5bsXgTzhhAjXgVRFb0HdlO2nctyn6hgUeH7BDvc2HZDWaPOFBYnOqFPL4Vg8jjAMYEYZAuwKezqxeUyubzEt7TSlddkvUbUKeRO4WS8aLwSRlwVsZJC2ncvS8cRC7e/8ORPflJKTYlvzdU7n9Qv/+xUbkCk=
  strategy: git
  app:
    heroku-prod: ifconfig-rs
    heroku-staging: ifconfig-rs-staging
  on:
    condition:
    - "$DEPLOY"
