[package]
name = "ifconfig-rs"
version = "0.0.1"
authors = ["Lukas Pustina <lukas@pustina.net>"]

description = "Yet another ifconfig / what's my IP clone"
repository = "https://github.com/lukaspustina/ifconfig-rs"
readme = "README.md"
license = "MIT"
keywords = ["ifconfig", "ip", "network", "web service"]
include = [
  "README.md",
  "LICENSE",
  "**/*.rs",
  "Cargo.toml",
]

[badges]
travis-ci = { repository = "lukaspustina/ifconfig-rs", branch = "master" }
appveyor = { repository = "lukaspustina/ifconfig-rs", branch = "master" }

[[bin]]
name = "ifconfig-rs"
path = "src/main.rs"

[dependencies]
clap = "2"
error-chain = "0.11.0-rc.2"
hyper = "0.10"
rocket = "0.3"
rocket_codegen = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"

[dependencies.rocket_contrib]
version = "0.3"
default-features = false
features = ["handlebars_templates"]

[dev-dependencies]
pretty_assertions = "0.1"

