[default]
port = 8000
limits = { form = "64 kB", json = "1 MiB" }
log_level = "normal"
project_name = "ifconfig-rs"
geoip_city_db = "data/GeoLite2-City.mmdb"
geoip_asn_db = "data/GeoLite2-ASN.mmdb"

[debug]
address = "0.0.0.0"
log = "normal"
base_url = "localhost"

[release]
address = "0.0.0.0"
base_url = "localhost"

[xforwarded]
address = "0.0.0.0"
runtime = "xforwarded"
project_name = "ip.pdt.sh"
base_url = "ip.pdt.sh"
log_level = "normal"
cli_colors = false
