version: 2.1

orbs:
  heroku: circleci/heroku@0.0.6

commands:
  rust_build:
    description: "Run cargo build workflow with specific Rust version"
    parameters:
      rust_channel:
        type: string
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v1-cargo-cache-<< parameters.rust_channel >>-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - run:
          name: Run all tests
          command: cargo test --all
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v1-cargo-cache-<< parameters.rust_channel >>-{{ arch }}-{{ checksum "Cargo.lock" }}
  heroku_deploy:
    description: "Deploys app to Heroku"
    parameters:
      app_name:
        type: string
    executor:
      heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          api-key: $HEROKU_API_KEY
          app-name: << parameters.app_name >>


jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - rust_build:
          rust_channel: nightly
  deploy-prod:
    steps:
      - heroku_deploy:
          app_name: ifconfig-rs
  deploy-staging:
    steps:
      - heroku_deploy:
          app_name: ifconfig-rs-staging


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: heroku-prod
          context: ifconfig-rs
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: heroku-staging
          context: ifconfig-rs
  cron:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build

