---
name: Continous Integration

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cargo Check
        run: cargo check --verbose

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cargo Clippy
        run: cargo clippy --verbose

  fmt:
    name: Cargo Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cargo Ftm
        run: cargo fmt  --check --verbose

  build-n-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cargo Build
        run: cargo build --verbose
      - name: Cargo Unit Test
        run: cargo test --lib --no-fail-fast

  integration-test:
    needs: [check, build-n-test]
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log into registry GHCR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: lukaspustina
          password: ${{ secrets.LP_GHCR_TOKEN }}
      - name: Build Docker Image and Run Tests
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          file: tests/Dockerfile.tests
          context: .
          push: false
