name: Docker Image CI

on:
  push:
    branches: [ "prod" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker images
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        push: true
        tags: ghcr.io/lukaspustina/ifconfig-rs:latest
